### ISSUE TITLE
你好，这个项目目前还可用吗

### ISSUE THREAD

**Issue by liwenjie119** [2512500960/zzu-minieap#2]
目前校园网客户端版本显示是6.84.2017.12.28，应该还能用吧

**Comment by liwenjie119** [comment]
啊，我看到还有一个路由器的项目，稍后我会编译一下固件看看是否能用

**Comment by 2512500960** [comment]
> 目前校园网客户端版本显示是6.84.2017.12.28，应该还能用吧

目前校网络中心要求windows客户端版本是6.84，要求的linux客户端版本是1.30/1.31。这个zzu-minieap模拟的认证报文就是linux客户端1.30版本的。目前还能用，至少我还在用。

**Comment by arbaleast** [comment]
minieap -u ******** -p ******** -n ******** --module printer --module rjv3 -e 20 --module printer --if-impl sockraw --service default
MiniEAP 0.92.1
Hamster Tian, 2016

[2020/9/12 10:36:07][E] 无法打开配置文件: No such file or directory (2)
[2020/9/12 10:36:07][W] 配置文件解析出错，请注意命令行参数是否完整
[2020/9/12 10:36:07][I] 
RJv3 for MiniEAP 0.92.1
V3 校验算法来自 hyrathb@GitHub
Hamster Tian, 2016

[2020/9/12 10:36:07][E] 无法打开 PID 文件: Permission denied (13)
[2020/9/12 10:36:07][I] MiniEAP 已退出



请问一下，问题出在哪了？

**Comment by 2512500960** [comment]
> minieap -u ******** -p ******** -n ******** --module printer --module rjv3 -e 20 --module printer --if-impl sockraw --service default
> MiniEAP 0.92.1
> Hamster Tian, 2016
> 
> [2020/9/12 10:36:07][E] 无法打开配置文件: No such file or directory (2)
> [2020/9/12 10:36:07][W] 配置文件解析出错，请注意命令行参数是否完整
> [2020/9/12 10:36:07][I]
> RJv3 for MiniEAP 0.92.1
> V3 校验算法来自 hyrathb@GitHub
> Hamster Tian, 2016
> 
> [2020/9/12 10:36:07][E] 无法打开 PID 文件: Permission denied (13)
> [2020/9/12 10:36:07][I] MiniEAP 已退出
> 
> 请问一下，问题出在哪了？

是root权限吗

**Comment by arbaleast** [comment]
不是，行，我试试

**Comment by arbaleast** [comment]
[2020/9/12 10:48:14][I] ========================
[2020/9/12 10:48:14][I] MiniEAP 0.92.1已启动
[2020/9/12 10:48:14][I] 正在查找认证服务器
[2020/9/12 10:48:14][W] 第二 DNS 地址获取错误。若认证失败，请用 --fake-dns2 指定第二 DNS 地址
[2020/9/12 10:48:14][I] We send one! 524 1512
[2020/9/12 10:48:14][I] We got one! 60 1512
[2020/9/12 10:48:14][I] 正在回应用户名请求
[2020/9/12 10:48:14][W] 第二 DNS 地址获取错误。若认证失败，请用 --fake-dns2 指定第二 DNS 地址
[2020/9/12 10:48:14][I] We send one! 540 1512
[2020/9/12 10:48:14][I] We got one! 60 1512
[2020/9/12 10:48:14][I] 正在回应密码请求
[2020/9/12 10:48:14][W] 第二 DNS 地址获取错误。若认证失败，请用 --fake-dns2 指定第二 DNS 地址
[2020/9/12 10:48:14][I] We send one! 573 1512
[2020/9/12 10:48:14][D] 字段格式错误，未发现特征值（偏移量 0x23）
[2020/9/12 10:48:14][I] 服务器通知：
[2020/9/12 10:48:14][I] 不允许使用的客户端类型!

**Comment by arbaleast** [comment]
谢谢，用root通过了，但是遇到了[2020/9/12 10:48:14][I] 不允许使用的客户端类型!
这个是因为客户端校验吗？

**Comment by 2512500960** [comment]
> 谢谢，用root通过了，但是遇到了[2020/9/12 10:48:14][I] 不允许使用的客户端类型!
> 这个是因为客户端校验吗？

是，我问问还在学校的同学吧，我毕业了。方便的话可以加个qq

**Comment by arbaleast** [comment]
好的，谢谢 qq是3309839520

**Comment by findyy99** [comment]
> 好的，谢谢 qq是3309839520

老哥，这个目前还能用吗

**Comment by 2512500960** [comment]
> 
应该是还可以的吧。

**Comment by findyy99** [comment]
> 应该是还可以的吧。

您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译

**Comment by 2512500960** [comment]
> > 应该是还可以的吧。
> 
> 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译

linux的话编译难度不大，mac不知道能不能用，没用过没试过。

**Comment by findyy99** [comment]
> > > 应该是还可以的吧。
> > 
> > 
> > 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译
> 
> linux的话编译难度不大，mac不知道能不能用，没用过没试过。

好吧，我还是老老实实用校园网的Wi-Fi吧 : (

**Comment by findyy99** [comment]
> > > 应该是还可以的吧。
> > 
> > 
> > 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译
> 
> linux的话编译难度不大，mac不知道能不能用，没用过没试过。

您好，目前我在虚拟机上装了OpenWrt，但是我把那个minieap4x86放在根目录里运行，提示找不到
<img width="302" alt="image" src="https://user-images.githubusercontent.com/26852735/142712570-7635535f-a7ef-45fe-8799-a520e17b079c.png">

**Comment by 2512500960** [comment]
> > > > 应该是还可以的吧。
> > > 
> > > 
> > > 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译
> > 
> > 
> > linux的话编译难度不大，mac不知道能不能用，没用过没试过。
> 
> 您好，目前我在虚拟机上装了OpenWrt，但是我把那个minieap4x86放在根目录里运行，提示找不到 <img alt="image" width="302" src="https://user-images.githubusercontent.com/26852735/142712570-7635535f-a7ef-45fe-8799-a520e17b079c.png">

感觉像是elf没对上，你用file命令查看文件属性，看下mini文件和任意一个能执行的elf文件（比如/usr/sbin/sshd），看下结果。github用户名是qq号。

**Comment by liwenjie119** [comment]
> > > > 应该是还可以的吧。
> > > 
> > > 
> > > 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译
> > 
> > 
> > linux的话编译难度不大，mac不知道能不能用，没用过没试过。
> 
> 您好，目前我在虚拟机上装了OpenWrt，但是我把那个minieap4x86放在根目录里运行，提示找不到 <img alt="image" width="302" src="https://user-images.githubusercontent.com/26852735/142712570-7635535f-a7ef-45fe-8799-a520e17b079c.png">

目前arm，x86，MIPS平台的openwrt插件都可用，我是直接编译到openwrt里去的

**Comment by findyy99** [comment]
> > > > > 应该是还可以的吧。
> > > > 
> > > > 
> > > > 您好，麻烦问一下这个编译对小白来说难度大吗，现在的release没有Mac版本的。我想试一下编译
> > > 
> > > 
> > > linux的话编译难度不大，mac不知道能不能用，没用过没试过。
> > 
> > 
> > 您好，目前我在虚拟机上装了OpenWrt，但是我把那个minieap4x86放在根目录里运行，提示找不到 <img alt="image" width="302" src="https://user-images.githubusercontent.com/26852735/142712570-7635535f-a7ef-45fe-8799-a520e17b079c.png">
> 
> 目前arm，x86，MIPS平台的openwrt插件都可用，我是直接编译到openwrt里去的

谢谢回复，前两天联系了作者，他已经编译了一个MIPS给我使用，已经连上了，感谢🙏！
