### ISSUE TITLE
你好，想请教一下连接掉线的问题

### ISSUE THREAD

**Issue by cx99325** [2512500960/zzu-minieap#4]
学长你好，今天尝试了一下目前认证没有问题，但是5分钟左右就会掉线，想请问下是哪里的问题呢？论坛搜了下有可能是心跳时间的问题，可是改动源码哪里可以改心跳间隔呢😂还望不吝赐教。

**Comment by 2512500960** [comment]
你运行的是哪个版本的源码程序，我记得之前开启源码里面的心跳功能了啊？ 参数-e 20代表20s发送一次心跳包
![image](https://user-images.githubusercontent.com/16852896/149343082-1e633175-5e0b-46de-ab75-b4d7f086fa8e.png)

**Comment by cx99325** [comment]
我是按readme里说的自己编译的openwrt版插件。git clone https://github.com/2512500960/zzu-minieap-openwrt.git
这个是加了心跳的吗？

**Comment by 2512500960** [comment]
还不行就加qq解决
